apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webapp 
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never
          volumeMounts: 
            - mountPath: /app
              name: backend-src-vol
          ports:
            - containerPort: 3000
      volumes:
        - name: backend-src-vol
          hostPath:
            path: src/
            type: Directory
# todo: create the rest of the application and write docs for huohuo
