apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels: app
        app: webapp
    spec:
      containers:
        - name: backend
          image: backend:latest
          volume: 
            - mountPath: /app
              name: backend-src-vol
          ports:
            - containerPort: 3000
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017
        - name: frontend
          image: frontend:latest
          ports: 8080
      volume:
        - name: backend-src-vol
          hostPath:
            /Users/ziliz/projects/clojuristic
          type:
            Directory
