apiVersion: v1
kind: Service
metadata:
  name: mongo 
  labels:
    app: myapp
spec:
  ports:
    - port: 27017 
  selector:
    app: myapp 
    tier: db 
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: myapp 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myapp-mongo
  labels:
    app: myapp 
spec:
  selector:
    matchLabels:
      app: myapp 
      tier: mongo 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp 
        tier: mongo 
    spec:
      containers:
      - image: mongo:4.2 
        name: mongo 
        command: ["-f", "/config/config.yaml"]
        # env:
        # - name: MYSQL_ROOT_PASSWORD
          # valueFrom:
            # secretKeyRef:
              # name: mysql-pass
              # key: password
        ports:
        - containerPort: 27017
          name: mongo 
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data 
        - name: /config 
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
