load("@rules_java//java:defs.bzl", "java_binary")

# This will build a Java binary for the srcs specified
java_binary(
    name = "MainEntrypoint",
    main_class = "src.main.MainEntry",
    srcs = glob(["src/main/*.java"]),
)
