load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "2.8"
RULES_JVM_EXTERNAL_SHA = "79c9850690d7614ecdb72d68394f994fef7534b292c4867ce5e7dec0aa7bdfad"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
maven_install(
    artifacts = [
        "com.google.inject:guice:4.1.0",
        "com.google.errorprone:error_prone_annotations:2.0.18",
        "com.google.j2objc:j2objc-annotations:1.1",
        "io.netty:netty-all:jar:4.1.51.Final",
        "org.mongodb:mongodb-driver:3.12.7"
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
)

maven_install(
    name = "netty_deps",
    artifacts = [
        "io.netty:netty-all:jar:4.1.51.Final",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
)

load("//:utils.bzl", "maven_deps")

maven_install(
    name = "javax",
    artifacts = [
        "javax.inject:javax.inject:1",
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://repo1.maven.org/maven2",
    ],
    fetch_sources = True,
)


maven_deps("graphql", 'com.graphql-java:graphql-java:15.0')
maven_deps("logging", "org.slf4j:slf4j-api:1.7.30")

#load("@maven//:compat.bzl", "compat_repositories")
#compat_repositories()
