storage:
   dbPath: "/home/zxiang/config/mongo/data"
   indexBuildRetry: true
   journal:
      enabled: true
      commitIntervalMs: 500
systemLog:
   destination: file
   path: "/home/zxiang/config/mongo/data/mongod.log"
   logAppend: true
processManagement:
   fork: true
net:
   bindIp: 127.0.0.1
   port: 27017

