storage:
   dbPath: "/data"
   indexBuildRetry: true
   journal:
      enabled: true
      commitIntervalMs: 500
systemLog:
   destination: file
   path: "/data/mongod.log"
   logAppend: true
net:
   bindIp: 127.0.0.1
   port: 27017

